name: linky
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  cloudinary_flutter: ^1.3.0
  cloudinary_url_gen: ^1.8.0
  cloudinary_public: ^0.23.1

dev_dependencies:
  dio: ^5.9.0
  feather_icons: ^1.2.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_map: ^8.2.1
  flutter_osm_plugin: ^1.4.2
  google_fonts: ^6.3.0
  google_places_autocomplete_text_field: ^2.0.3
  http: ^1.5.0
  ionicons: ^0.2.2
  jwt_decoder: ^2.0.1
  latlong2: ^0.9.1
  material_floating_search_bar_2: ^0.5.0
  modal_bottom_sheet: ^3.0.0
  new_loading_indicator: ^1.0.2
  search_map_place_updated: ^0.1.0
  shared_preferences: ^2.5.3
  geolocator: ^12.0.0
  phone_form_field: ^10.0.8
  flutter_native_splash: ^2.4.6
  flutter_paystack_plus: ^2.2.2
  flutter_paystack_max: ^1.0.6
  choice: ^2.3.2
  currency_formatter: ^2.3.0
  timeago: ^3.7.1
  geocoding: ^4.0.0
  flutter_typeahead: ^5.2.0
  flutter_keyboard_visibility: ^6.0.0
  pocketbase: ^0.23.0+1
  web_socket_channel: ^3.0.3
  price_text: ^0.0.5
  intl: ^0.20.2
  skeletonizer: ^2.1.0+1
  url_launcher: ^6.1.14
  timer_count_down: ^2.2.2
  action_slider: ^0.7.0
  image_picker: ^1.0.4
  animated_toggle_switch: ^0.8.5
  flutter_launcher_icons: ^0.14.4
  mapbox_maps_flutter: ^2.12.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/linki.png
